name: KayraExport Microservices CI/CD Pipeline

on:
  push:
    branches: [ "test/v1.0.0", "prod/v1.0.0" ]
  pull_request:
    branches: [ "prod/v1.0.0" ]

jobs:
  build-and-test:
    name: Build & Docker Check
    runs-on: ubuntu-latest

    steps:
    - name:  Kodu Klonla (Checkout)
      uses: actions/checkout@v4

    - name:  .NET 9 Kurulumu
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name:  Docker Compose Build Testi
      run: docker compose build

    - name: Başarı Bildirimi
      run: echo "Tüm mikroservisler başarıyla derlendi ve Docker imajları hatasız oluşturuldu!"